### ISSUE TITLE
What is the function of the resourceType in the EditConfig? [question]

### ISSUE THREAD

**Issue by davidjgonzalez** [adobe/aem-react-editable-components#131]
**Describe the bug**

What is the function of the resourceType in the EditConfig

```
const TextEditConfig = {    
  emptyLabel:  'Text',
  isEmpty: () => {},
  resourceType: "wknd-app/components/text"
};
```

It doesn't seem to effect the App if i remove it (and it still requires a MapTo(..))

**Comment by iamdavidjackson** [comment]
So that is an optional parameter base on the Typescript type for Config 
https://github.com/adobe/aem-react-editable-components/blob/8d06907e94d8f6a33e47e4dbda6111170c0d2d71/src/types/EditConfig.ts#L33-L38

The only place that I can see if being used is in the EditableComponent here:

https://github.com/adobe/aem-react-editable-components/blob/8d06907e94d8f6a33e47e4dbda6111170c0d2d71/src/core/EditableComponent.tsx#L71-L83

This shows that it will just be added as data attributes on the wrapper div.  I am assuming it's just to make it easier to figure out which component is for which resourceType when you're debugging and looking at the code.

**Comment by davidjgonzalez** [comment]
Yes, this is ~ what I was able to deduce as a well. I thought it might me functional in some capacity that I didn't understand. -- ex. Wrt yo automatic mapping of components to RTs. Sounds like this is a largely cosmetic aspect.

**Comment by sharanyavinod** [comment]
@davidjgonzalez It is required in the case of [virtual components](https://experienceleague.adobe.com/docs/experience-manager-65/developing/spas/spa-edit-external.html?lang=en#virtual-leaf-components). If the content doesnt yet exist within AEM, this config is used to determine what dialog to display on edit of the placeholder, and what kind of node to create/save on new content input. For all other use cases, as mentioned already, it is purely optional.
